### ISSUE TITLE
attribute support

### ISSUE THREAD

**Issue by Cj-bc** [Cj-bc/brick-shgif#1]
Support adding attributes to each char

# things to think

- [ ] how to define them in YAML file

**Comment by Cj-bc** [comment]
maybe I'll add `attr` key to each `frame` like:

```yaml
data:
  - timestamp: 0
    contents:
      - "Red"
      - "Bg Red"
      - "Bold"
    attr:
      - "rrr"
      - "RRRRRR"
      - "****"
```

Each`Attr` is either:
- defined by default
- defined in each file

**Comment by Cj-bc** [comment]
Whichever I take, there should be some way to define Attrs. (i.e. `{foreground: red, background: green, bold, blink}`)
More than one attributes could be assigned to one character. So I should find way to define those combinations by one char.

**Comment by Cj-bc** [comment]
Draft:

```yaml
  - timestamp: 0
    contents: |-
              anchor
              #    # ###### #      #        ##
              #    # #      #      #      :#  #:
              #    # #      #      #      #.  .#
              #    # #      #      #      #    #
              ###### ###### #      #      #    #
              #    # #      #      #      #    #
              #    # #      #      #      #.  .#
              #    # #      #      #      :#  #:
              #    # ###### ###### ######   ##
    attributes:
      - range: 6
        binary: "0x"
      - range: 6
        fg:
          type: ISO
          value: 2
```
