### ISSUE TITLE
Containerのフォーマット

### ISSUE THREAD

**Issue by Cj-bc** [Cj-bc/brick-shgif#19]
`Container`のファイルフォーマットをどうするかについて

# 決めたい内容

大きく分けて二つ

- なんの情報を入れるか
- `Shgif`のファイルフォーマットの拡張にするか否か

## なんの情報を入れるか

現在わかっていることは以下の通り

必須な情報:
- 格納する`Shgif`達のパス
- 格納する`Shgif`達それぞれのオフセット
- バージョン

必要かわからない情報:
- 筆者
- タイトル
- フォーマット

## `Shgif`のファイルフォーマットの拡張にするか否か

した場合のメリット:
- 定義が一つにまとまるのでわかりやすい？

した場合のデメリット:
- `Shgif`のデコードの際に弾く必要が出てくるかも？
- `Container`と`Shgif`の概念が混ざるとわかりづらいかも知れない

**Comment by Cj-bc** [comment]
拡張フォーマットにするか否かは、デメリットの方が明確に存在するのに対してメリットが浮かばないので「拡張しない」ということで決定

**Comment by Cj-bc** [comment]
# なんの情報を入れるか

## タイトルについて

タイトルは、個別のShgifにて設定されているもので十分であればつける必要がない
しかし、複数を組み合わせて一つの作品にする性質上、別の命名をした方が適切な時もあると思う。
なので、タイトルは入れることにしたいと思う。

## 筆者
いわゆるリミックス等したときには筆者名を書いておいた方が良いと思う。
なので入れる方が良いかと

## フォーマット
インラインのものを作るか否かによって変わる
インラインは便利かも知れないが、`Container`の役割が「再利用性」であることを考えるとあまり意味を持たない
よって、作らなくてもいいかなと思っている

**Comment by Cj-bc** [comment]
```yaml
title: <title>
author: <author>
version: <version>
data:
  - path: <path-of-shgif>
    offset: <offset-of-shgif>
  ...
```
