### ISSUE TITLE
Use biggest 'timestamp' in yaml to loop

### ISSUE THREAD

**Issue by Cj-bc** [Cj-bc/brick-shgif#2]
### Current implementation

- Use timestamp from latest frame

### Problem of current one

If frames are not sorted by timestamp, some frames might lack.

```yaml
title: exploit test for issue 2
author: Cj-bc
format: Page
width: 15
heigh: 1
data:
  - timestamp: 0
    contents:
      - "this is visible"
  - timestamp: 10
    contents:
      - "visible 2"
  - timestamp: 20
    contents:
      - "not visible"
  - timestamp: 15
    contents:
      - "This BAD FRAME"
```

![brick-shgif-bad-frame](https://user-images.githubusercontent.com/16875061/70912447-5051c080-2057-11ea-945d-a6535863d21d.gif)
