### ISSUE TITLE
Use multiline-string for contents

### ISSUE THREAD

**Issue by Cj-bc** [Cj-bc/brick-shgif#7]
We have some way to write multiline-string in YAML
It might be more readable

For example, [example/shgifs/shgif-v2-format-example-page.yaml](https://github.com/Cj-bc/brick-shgif/blob/master/example/shgifs/shgif-v2-format-example-page.yaml) will be:
```yaml
data:
  - timestamp: 0
    contents: |-
      #    # ###### #      #        ##
      #    # #      #      #      :#  #:
      #    # #      #      #      #.  .#
      #    # #      #      #      #    #
      ###### ###### #      #      #    #
      #    # #      #      #      #    #
      #    # #      #      #      #.  .#
      #    # #      #      #      :#  #:
      #    # ###### ###### ######   ##
  - timestamp: 100
    contents: |-
             #    # ###### #      #
             #    # #      #      #
             #    # #      #      #
             #    # #      #      #
             ###### ###### #      #
             #    # #      #      #
             #    # #      #      #
             #    # #      #      #
             #    # ###### ###### ######
  - timestamp: 200
    contents: |-
        ##         #    # ###### #
      :#  #:       #    # #      #
      #.  .#       #    # #      #
      #    #       #    # #      #
      #    #       ###### ###### #
      #    #       #    # #      #
      #.  .#       #    # #      #
      :#  #:       #    # #      #
        ##         #    # ###### ######
  - timestamp: 300
    contents: |-
      #       ##         #    # ######
      #     :#  #:       #    # #
      #     #.  .#       #    # #
      #     #    #       #    # #
      #     #    #       ###### ######
      #     #    #       #    # #
      #     #.  .#       #    # #
      #     :#  #:       #    # #
      #####   ##         #    # ######
  - timestamp: 400
    contents: |-
      #     #       ##         #    #
      #     #     :#  #:       #    #
      #     #     #.  .#       #    #
      #     #     #    #       #    #
      #     #     #    #       ######
      #     #     #    #       #    #
      #     #     #.  .#       #    #
      #     #     :#  #:       #    #
      ##### #####   ##         #    #
  - timestamp: 500
    contents: |-
      ######  #     #       ##
      #       #     #     :#  #:
      #       #     #     #.  .#
      #       #     #     #    #
      ######  #     #     #    #
      #       #     #     #    #
      #       #     #     #.  .#
      #       #     #     :#  #:
      ######  ##### #####   ##
  - timestamp: 600
    contents: |-
      ######  #     #       ##
      #       #     #     :#  #:
      #       #     #     #.  .#
      #       #     #     #    #
      ######  #     #     #    #
      #       #     #     #    #
      #       #     #     #.  .#
      #       #     #     :#  #:
      ######  ##### #####   ##
```

https://qiita.com/jerrywdlee/items/d5d31c10617ec7342d56

**Comment by Cj-bc** [comment]
It might allow us to quit doing escaping
![スクリーンショット 2020-02-03 18 33 36](https://user-images.githubusercontent.com/16875061/73641717-c962b100-46b3-11ea-9632-16e2916c6f7e.png)

**Comment by Cj-bc** [comment]
related codes:

https://github.com/Cj-bc/brick-shgif/blob/f8a2072a59cfec228f849b63af47b68aa85a2ed8/src/Shgif/Type.hs#L77-L81

**Comment by Cj-bc** [comment]
This require only a little change.
```diff
  parseContents :: Value -> Parser [String] 
- parseContents = withArray "contents" $ \a -> return $ V.toList $ V.map (toStr) a 
-     where 
-         toStr (String a) = unpack a 
+ parseContents = withText (lines . unpack)
```

**Comment by Cj-bc** [comment]
And should fix some examples and others which I made before.
It's not hard to support old format, but will make maintenance harder.
So I won't support old one.

Files to fix:
- [x] [example-in-shgif-format.yaml](example/shgifs/example-in-shgif-format.yaml)
- [x] [face_blinking.yaml](example/shgifs/face_blinking.yaml)
- [x] [rolling-cycle.yaml](example/shgifs/rolling-cycle.yaml)
- [x] [shgif-v2-format-example-page.yaml](example/shgifs/shgif-v2-format-example-page.yaml)


- [x] [AAs/face2](https://github.com/Cj-bc/AAs/blob/master/faces/face2.yaml)

This is not implemented. So no need to update.
- [shgif-v2-format-example-plot.yaml](example/shgifs/shgif-v2-format-example-plot.yaml)

Those uses old version of Brick-shgif. Update when they update the library.
- [ ] [AAs/face3](https://github.com/Cj-bc/AAs/tree/master/faces/face3)
- [ ] [AAs/fanarts/inugami-korone-kadomatu](https://github.com/Cj-bc/AAs/tree/master/fanarts/inugami-korone/kadomatu/shgif)

**Comment by Cj-bc** [comment]
I' DO THIS ;)

**Comment by Cj-bc** [comment]
Oops, We need to have letter at the top-left of each frame
I mean, both of following are illegal.

```yaml
# No letters on the first line
contents: |-

                     ABC
# No letter at the begining of the line
contents: |-
                           weo
                     ABC
```
